version: "3.9"

services: 
    grafana:
        container_name: azion-metrics-grafana
        image: grafana/grafana:latest
        ports:
            - 3000:3000
        restart: unless-stopped
        volumes:
            - ./grafana/datasources:/etc/grafana/provisioning/datasources
            - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
        environment:
            # Azion Personal Token
            TOKEN: $PERSONAL_TOKEN
            # Container tzdata
            TZ: "UTC"
            # Grafana
            GF_AUTH_DISABLE_LOGIN_FORM: "true"
            GF_AUTH_ANONYMOUS_ENABLED: "true"
            GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
            GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/etc/grafana/provisioning/dashboards/home/dashboard.json"
            # stable Infinity plugin
            # GF_INSTALL_PLUGINS: "yesoreyeram-infinity-datasource"
            # bleeding edge Infinity plugin
            GF_INSTALL_PLUGINS: "https://github.com/yesoreyeram/grafana-infinity-datasource/releases/download/v1.0.1/yesoreyeram-infinity-datasource-1.0.1.zip;yesoreyeram-infinity-datasource"
